module RbsMiniMagick
  module ImageMagick
    class Option
      attr_reader normalized_name: String

      def initialize: (name: String, args: Array[String]) -> void

      def args_empty?: () -> bool

      private

      attr_reader name: String

      attr_reader args: Array[String]
    end
  end
end
