module RbsMiniMagick
  module ImageMagick
    class ToolUsage
      def self.build_by_raw_usage: (String, String) -> ImageMagick::ToolUsage

      attr_reader name: String

      attr_reader options: Array[Option]

      def initialize: (name: String, options: Array[Option]) -> void

      def args_empty?: () -> bool

      private

      def self.build_option_by_raw_line: (String) -> Option?
    end
  end
end
