module RbsMiniMagick
  module ImageMagick
    class UsageParser
      def initialize: (raw_usage: String) -> void

      def run: () -> Array[CommandLineOption]

      private

      attr_reader raw_usage: String

      def parse_raw_command_line_options: () -> Array[String]

      def build_command_line_option: (String) -> CommandLineOption
    end
  end
end
