require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - "typecheck/**/*.rb"
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false
