module RbsMiniMagick
  module Builders
    class ToolInterface
      type options = Array[::RbsMiniMagick::ImageMagick::CommandLineOption]

      def initialize: (tool_name: String, options: options) -> void

      private

      attr_reader tool_name: String

      attr_reader options: options
    end
  end
end
