module RbsMiniMagick
  class Builder
    def initialize: (mini_magick_version: String?) -> void

    def run: () -> String

    private

    attr_reader mini_magick_version: Gem::Version

    def tool_names_and_flows: () -> [Array[String], Array[Flows::_Flow]]

    def build_tool_usages: (Array[String]) -> Array[ImageMagick::ToolUsage]
  end
end
