module RbsMiniMagick
  class Generator
    def initialize: (mini_magick_version: Gem::Version?, output_dir: String?) -> void

    def run: () -> void

    private

    attr_reader mini_magick_version: Gem::Version

    attr_reader output_dir: Pathname

    attr_reader output_path: Pathname
  end
end
