name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.3'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup
        run: bin/setup
      - name: Run rubocop
        run: rake rubocop
      - name: Run rspec
        run: rake rspec
      - name: Run yard
        run: rake yard
      - name: Run typecheck for lib
        run: rake typecheck:lib
      - name: Run typecheck for all typecheck/<version> dirs
        run: rake typecheck:all_version
